# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:03
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('cover', models.ImageField(upload_to=books.models.upload_location)),
                ('book_file', models.FileField(upload_to=books.models.upload_location)),
                ('book_type', models.CharField(default='ebook', max_length=120)),
                ('authors', models.ManyToManyField(blank=True, to='books.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
