# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 12, 20, 25, 26, 714777, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 12, 20, 26, 0, 816874, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 12, 20, 26, 6, 987844, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
