# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:33
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160512_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to=books.models.upload_location),
        ),
    ]
