# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160512_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
