# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20160513_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
