# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
