# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20160520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, default='Ebook', max_length=120),
        ),
    ]
